---
- name: Remove a VM and all resources that were autocreated
  azure_rm_virtualmachine:
    resource_group: "{{ item.resourcegroup_name }}"
    name: "{{ item.name }}"
    remove_on_absent: all_autocreated
    state: absent
  loop: "{{ vm }}"
  register: az_instances
  async: 7200
  poll: 0

- name: Wait for instance termination to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: ec2_jobs
  until: ec2_jobs.finished
  retries: 300
  loop: "{{ az_instances.results }}"
  when: item.ansible_job_id is defined

- name: Delete a resource group including resources it contains
  azure_rm_resourcegroup:
    name: "{{ item.name }}"
    force_delete_nonempty: yes
    state: absent
  loop: "{{ resource_groups }}"
  when: destroy_networking
