---
- name: "Deploy webapp"
  ansible.builtin.get_url:
    url: "https://drive.google.com/uc?export=download&id=1w9ss5okctnjUvRAxhPEPyC7DmbUwmbhb"
    dest: "{{ jws_home }}/webapps/info.war"
  notify: "Restart Tomcat service"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: "Ensure JWS is back up before accessing the webapp."
  ansible.builtin.wait_for:
    port: 8080

- name: "Check that webapp is available"
  ansible.builtin.get_url:
    url: "http://localhost:8080/info/"
    dest: /tmp/res.txt
  changed_when: false
