---
- name: Create kubevirt VMs
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Create resource
      include_role:
        name: 'kubevirt'
        tasks_from: "{{ action | default('main') }}"
      vars:
        ssh_key_path: id_rsa_aws.pub
        vm_name: jws4
