---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  vars:
    jws_setup: True
    jws_version: 5.6.0
    jws_native: false
    jws_java_version: 1.8.0
    jws_systemd_enabled: True
    jws_service_name: jws
    jws_apps_to_remove: ROOT,examples
    jws_selinux_enabled: False
    jws_apply_patches: True
    jws_patch_version: 5.6.2
    jws_listen_http_bind_address: 0.0.0.0
  collections:
    - redhat.jws
  pre_tasks:

    - name: "Retrieve JWS assets from: {{ repo_server }}."
      ansible.builtin.include_tasks: download_assets.yml

  tasks:
    - name: "Ensure JWS {{ jws_version }} is installed."
      ansible.builtin.include_role:
        name: jws

  post_tasks:
    - name: "Ensure JWS is updated to latest available version: {{ jws_patch_version }}."
      ansible.builtin.include_role:
        name: jws
        tasks_from: apply_cp/main.yml

    - name: "Deploy apps."
      ansible.builtin.include_tasks: app_deploy.yml
