---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  vars:
    jws_setup: True
    jws_version: 5.7.0
    jws_native: false
    jws_java_version: 1.8.0
    jws_systemd_enabled: True
    jws_service_name: jws
    jws_apps_to_remove: ROOT,examples
    jws_selinux_enabled: False
  collections:
    - redhat.jws
  pre_tasks:

    - name: "Retrieve JWS assets from: {{ repo_server }}."
      ansible.builtin.include_tasks: download_assets.yml

    - name: "Ensure existing JWS service is stopped."
      ansible.builtin.service:
        name: jws
        state: stopped
  tasks:
    - name: "Ensure JWS {{ jws_version }} is installed."
      ansible.builtin.include_role:
        name: jws

  post_tasks:

    - name: "Deploy apps."
      ansible.builtin.include_tasks: app_deploy.yml
