plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - jws-demo-uksouth-rg
auth_source: auto
leading_separator: no
plain_host_names: yes
keyed_groups:
 - key: tags.Role
 - key: tags.Site
 - key: tags.Region
 - key: tags.Cloud
